## @param custonName allows to set a custom resource name for the k8 resources in the chart
##        Default to .Release.Name .Chart.Name
customName: 'templating2'

## @param replicaCount Number of nginx replicas today
replicaCount: 3
## @param environment environment to apply
environment: production

## Settings for NGINX image
## @param image.name Nginx image same to use
## @param image.tag Nginx image tag to use
image: 
  name: nginx
  tag: 1.29.2

## NGINX container ports
##
## @param containerPorts.http  The port where the container is connected
containerPorts:
  http: 80

## Settings for NGINX image
## services is a map with the following schema
##
## @param services["*""].type The type of service in front of the service
## @param services["*""].port The port where the service is receiving the data

services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 3000


## Settings for NGINX container securityContext
##
## @param securityContext.runAsUser 
## @param securityContext.fsGroup
securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 2000