## @param replicaCount Number of nginx replicas today
replicaCount: 2

## Settings for NGINX image
## @param image.name Nginx image same to use
## @param image.tag Nginx image tag to use
image: 
  name: nginx
  tag: 1.29.2

## NGINX container ports
##
## @param containerPorts.http  The port where the container is connected
containerPorts:
  http: 80


## Settings for NGINX image

## @param service.enabled Wheter to depploy the service or not
## @param service.type The type of service in front of Nginx
## @param service.port The port where the service is receiving the data

service:
  enabled: false
  type: NodePort
  port: 8080  